/**
 * Hello UI Tool
 * 
 * A simple greeting component that demonstrates basic HTML rendering.
 * This is the simplest example of an MCP-UI tool.
 */

import { z } from 'zod';
import { createHtmlResource, wrapWithStyles } from '../lib/ui-helpers';

// Tool definition
export const helloUITool = {
  name: 'hello_ui',
  description: 'Display a friendly greeting message with customizable name and theme',
  inputSchema: z.object({
    name: z.string().optional().describe('Name to greet (default: "World")'),
    theme: z.enum(['light', 'dark', 'gradient']).optional().describe('Color theme'),
  }),
};

export type HelloUIInput = z.infer<typeof helloUITool.inputSchema>;

// Tool handler
export function handleHelloUI(input: HelloUIInput) {
  const name = input.name || 'World';
  const theme = input.theme || 'gradient';

  const themes = {
    light: {
      bg: 'white',
      text: '#1e293b',
      border: '1px solid #e2e8f0'
    },
    dark: {
      bg: '#1e293b',
      text: 'white',
      border: 'none'
    },
    gradient: {
      bg: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      text: 'white',
      border: 'none'
    }
  };

  const t = themes[theme];

  const html = wrapWithStyles(`
    <div style="
      padding: 32px;
      background: ${t.bg};
      color: ${t.text};
      border-radius: 16px;
      border: ${t.border};
      text-align: center;
    ">
      <h1 style="margin: 0 0 12px 0; font-size: 32px; font-weight: 700;">
        Hello, ${name}!
      </h1>
      <p style="margin: 0 0 20px 0; opacity: 0.9; font-size: 16px;">
        Welcome to the MCP-UI Playground. This interactive UI was generated by an AI tool.
      </p>
      <div style="
        display: inline-block;
        padding: 8px 16px;
        background: rgba(${theme === 'light' ? '0,0,0' : '255,255,255'},0.1);
        border-radius: 8px;
        font-family: monospace;
        font-size: 13px;
      ">
        mimeType: text/html | theme: ${theme}
      </div>
    </div>
  `);

  return createHtmlResource({
    uri: `ui://hello/${name.toLowerCase().replace(/\s+/g, '-')}`,
    html,
    title: `Hello ${name}`,
    description: 'A friendly greeting component'
  });
}
